events {}

http {
    upstream back-end {
        server back-end1:5252;
        server back-end2:5252;
    }

    server {
        listen 80;

        location /api {
            proxy_pass http://back-end;
        }

        location / {
            proxy_pass http://front-end:9000;
        }
    }
}
