version: "3"

services:
  back-end1:
    build:
      context: ./
      dockerfile: Dockerfile

  back-end2:
    build:
      context: ./
      dockerfile: Dockerfile

  front-end:
    build:
      context: ./
      dockerfile: front-end.Dockerfile

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
